[2025-01-19T20:36:52.611+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.load_md_account_d manual__2025-01-19T20:36:31.680662+00:00 [queued]>
[2025-01-19T20:37:01.624+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.load_md_account_d manual__2025-01-19T20:36:31.680662+00:00 [queued]>
[2025-01-19T20:37:01.626+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-19T20:37:17.623+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_md_account_d> on 2025-01-19 20:36:31.680662+00:00
[2025-01-19T20:37:17.670+0000] {standard_task_runner.py:60} INFO - Started process 173 to run task
[2025-01-19T20:37:17.710+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'load_md_account_d', 'manual__2025-01-19T20:36:31.680662+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp4p4jzzk1']
[2025-01-19T20:37:17.778+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask load_md_account_d
[2025-01-19T20:37:18.474+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.load_md_account_d manual__2025-01-19T20:36:31.680662+00:00 [running]> on host b8f36627e35c
[2025-01-19T20:37:19.197+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dmitry' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='load_md_account_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T20:36:31.680662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-19T20:36:31.680662+00:00'
[2025-01-19T20:37:19.676+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:20.040+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:20.230+0000] {sql.py:450} INFO - Running statement: 
    SELECT ds.upsert_table('md_account_d', 'tmp_md_account_d');
    , parameters: None
[2025-01-19T20:37:20.261+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-19T20:37:25.352+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:25.640+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO logs.data_load_log (process_name, start_time, end_time, status, rows_loaded, message)
        VALUES (%s, %s, %s, %s, %s, %s)
        , parameters: ('Load process for md_account_d', datetime.datetime(2025, 1, 19, 20, 37, 19, 222615), datetime.datetime(2025, 1, 19, 20, 37, 25, 274272), 'Completed', 112, '112 rows affected.')
[2025-01-19T20:37:25.745+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-19T20:37:25.823+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:26.002+0000] {sql.py:450} INFO - Running statement: DROP TABLE IF EXISTS ds.tmp_md_account_d;, parameters: None
[2025-01-19T20:37:26.034+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-19T20:37:26.081+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=load_md_account_d, execution_date=20250119T203631, start_date=20250119T203652, end_date=20250119T203726
[2025-01-19T20:37:26.232+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-19T20:37:26.379+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
