[2025-01-19T20:37:19.897+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.load_ft_balance_f scheduled__2025-01-18T00:00:00+00:00 [queued]>
[2025-01-19T20:37:19.951+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.load_ft_balance_f scheduled__2025-01-18T00:00:00+00:00 [queued]>
[2025-01-19T20:37:19.953+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-19T20:37:20.051+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_ft_balance_f> on 2025-01-18 00:00:00+00:00
[2025-01-19T20:37:20.086+0000] {standard_task_runner.py:60} INFO - Started process 176 to run task
[2025-01-19T20:37:20.125+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'load_ft_balance_f', 'scheduled__2025-01-18T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp_cj3i6t2']
[2025-01-19T20:37:20.135+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask load_ft_balance_f
[2025-01-19T20:37:20.478+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.load_ft_balance_f scheduled__2025-01-18T00:00:00+00:00 [running]> on host b8f36627e35c
[2025-01-19T20:37:20.664+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dmitry' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='load_ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-18T00:00:00+00:00'
[2025-01-19T20:37:20.718+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:20.917+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:21.029+0000] {sql.py:450} INFO - Running statement: 
    SELECT ds.upsert_table('ft_balance_f', 'tmp_ft_balance_f');
    , parameters: None
[2025-01-19T20:37:21.044+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-19T20:37:26.091+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:26.234+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO logs.data_load_log (process_name, start_time, end_time, status, rows_loaded, message)
        VALUES (%s, %s, %s, %s, %s, %s)
        , parameters: ('Load process for ft_balance_f', datetime.datetime(2025, 1, 19, 20, 37, 20, 669502), datetime.datetime(2025, 1, 19, 20, 37, 26, 65501), 'Completed', 114, '114 rows affected.')
[2025-01-19T20:37:26.245+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-19T20:37:26.274+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:26.504+0000] {sql.py:450} INFO - Running statement: DROP TABLE IF EXISTS ds.tmp_ft_balance_f;, parameters: None
[2025-01-19T20:37:26.547+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-19T20:37:26.611+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=load_ft_balance_f, execution_date=20250118T000000, start_date=20250119T203719, end_date=20250119T203726
[2025-01-19T20:37:26.777+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-19T20:37:26.840+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
